export type {
  RemediationPriority,
  RemediationStatus,
  RemediationSource,
  RemediationCategory,
  RemediationItem,
  SourceReference,
  AffectedAssetInfo,
  AssigneeInfo,
  RemediationTimeline,
  SLAConfig,
  EscalationLevel,
  RemediationSolution,
  RemediationStep,
  EffortEstimate,
  VerificationInfo,
  VerificationCheck,
  VerificationEvidence,
  WorkflowState,
  WorkflowTransition,
  WorkflowHistoryEntry,
  ApprovalRecord,
  RemediationMetrics,
  RemediationDashboard,
  RemediationSummary,
  SLAComplianceStats,
  RemediationTrend,
  RemediationQuery,
  RemediationPlan,
  RemediationTemplate,
  RemediationEventHandler,
} from './types.js';

export {
  RemediationEngine,
  createRemediationEngine,
} from './engine.js';
